In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
datafile = "LoansTrainingSetV2.csv"
raw_data = pd.read_csv(datafile, header=0)

/Users/Jerry/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2705: DtypeWarning: Columns (10,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
raw_data.head(20)

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,6cf51492-02a2-423e-b93d-676f05b9ad53,7c202b37-2add-44e8-9aea-d5b119aea935,Charged Off,12232,Short Term,7280.0,< 1 year,Rent,46643.0,Debt Consolidation,777.39,18.0,10.0,12,0,6762,7946,0.0,0.0
1,552e7ade-4292-4354-9ff9-c48031697d72,e7217b0a-07ac-47dd-b379-577b5a35b7c6,Charged Off,25014,Long Term,7330.0,10+ years,Home Mortgage,81099.0,Debt Consolidation,892.09,26.7,NaN,14,0,35706,77961,0.0,0.0
2,9b5e32b3-8d76-4801-afc8-d729d5a2e6b9,0a62fc41-16c8-40b5-92ff-9e4b763ce714,Charged Off,16117,Short Term,7240.0,9 years,Home Mortgage,60438.0,Home Improvements,1244.02,16.7,32.0,11,1,11275,14815,1.0,0.0
3,5419b7c7-ac11-4be2-a8a7-b131fb6d6dbe,30f36c59-5182-4482-8bbb-5b736849ae43,Charged Off,11716,Short Term,7400.0,3 years,Rent,34171.0,Debt Consolidation,990.94,10.0,NaN,21,0,7009,43533,0.0,0.0
4,1450910f-9495-4fc9-afaf-9bdf4b9821df,70c26012-bba5-42c0-8dcb-75295ada31bb,Charged Off,9789,Long Term,6860.0,10+ years,Home Mortgage,47003.0,Home Improvements,503.71,16.7,25.0,13,1,16913,19553,1.0,0.0
5,7e9f6759-6a13-48ef-adfa-ef9fbcfcfcc8,05301ee5-29ec-48b6-b3e5-0813ea25d684,Charged Off,11911,Short Term,7420.0,2 years,Home Mortgage,70475.0,other,886.81,17.7,NaN,13,0,28212,59897,0.0,0.0
6,c2b0aa3e-555b-441b-a4aa-e0e4a52c87d3,db3e74ec-2123-4608-be8d-a93e98cabfcf,Charged Off,28988,Short Term,7420.0,3 years,Home Mortgage,58074.0,Debt Consolidation,871.11,22.8,NaN,9,0,14423,54018,0.0,0.0
7,233e0119-6dfe-47c0-a212-b4cc00371c8d,def66e46-951e-4bff-bf96-87ae6e092e19,Charged Off,17705,Long Term,6630.0,3 years,Own Home,49180.0,Debt Consolidation,274.59,30.2,NaN,10,1,4252,25012,1.0,0.0
8,fc9d109b-15c2-4fe3-b7d8-27610b89f80b,f54c53e4-acd7-4e29-8f55-d2a247a4b62a,Charged Off,16812,Short Term,7360.0,7 years,Rent,50945.0,Debt Consolidation,590.12,14.6,NaN,9,0,12903,15379,0.0,0.0
9,35ee60ed-df2d-4d3a-98ba-03d944d65c74,93cbb4b9-4e88-4b93-8beb-a2a00d415cd5,Charged Off,9796,Long Term,6720.0,< 1 year,Rent,58776.0,Debt Consolidation,666.13,9.4,17.0,12,0,4939,15198,0.0,0.0
10,9634dd33-b16d-49f8-b9f6-2d9e1578798c,0d82eca5-ee60-4ebe-8387-54f1153a326f,Charged Off,19838,Long Term,7010.0,6 years,Home Mortgage,79352.0,Debt Consolidation,$1051.41,14.3,6.0,13,0,15780,22511,0.0,0.0
11,7d8dddd0-3c5a-4e37-a8b6-1d7f20f68397,00647781-a770-4ba8-8259-48473ffe2a56,Charged Off,18392,Long Term,7310.0,1 year,Rent,44959.0,Debt Consolidation,569.48,15.4,NaN,7,0,7085,11750,0.0,0.0
12,0779025a-3e68-4c58-bec2-8ca929207701,356e7d80-a879-4ee1-8023-e7b007dd9381,Charged Off,29496,Long Term,6850.0,3 years,Rent,76690.0,Debt Consolidation,1329.29,32.2,NaN,10,0,27643,44801,0.0,0.0
13,30931f26-c9a5-43c4-a724-24f5b1fde039,84f232ce-7738-4b84-9834-84f1735856aa,Charged Off,34276,Long Term,6280.0,10+ years,Home Mortgage,141019.0,other,2632.36,19.9,14.0,19,0,20223,31747,0.0,0.0
14,18e58e4b-90fc-4248-99f6-02ed33e8310f,a415393e-38d1-4622-aea9-cd9b6addc3c2,Charged Off,18230,Short Term,7470.0,5 years,Rent,151920.0,Business Loan,778.59,26.4,NaN,9,0,5663,29039,0.0,0.0
15,cead3a3f-1294-4558-9688-60b92eb2d369,aa26c11c-174a-4f04-938f-5c07fe83d8f3,Charged Off,19660,Long Term,7310.0,< 1 year,Rent,58980.0,Debt Consolidation,973.17,15.6,NaN,5,0,23917,33829,0.0,0.0
16,18cf82cd-f0e6-452e-8429-2a1e70b056ec,a02200bf-f505-4223-aec7-2d1ae72c4426,Charged Off,24341,Long Term,7200.0,3 years,Rent,99392.0,Debt Consolidation,2360.55,17.1,NaN,8,0,16604,21288,0.0,0.0
17,1e3cabdc-ce1c-4449-bbd2-282fea49ab00,22e2f182-2ef4-4ec2-ba19-e601ecf13118,Charged Off,21350,Long Term,7320.0,10+ years,Rent,58626.0,small_business,723.05,15.0,NaN,4,0,4085,4886,0.0,0.0
18,286127c0-04c4-43f9-9bf5-2bc4d691bfa6,a6ce9c02-ea44-4e7b-a86d-7f10ad518930,Charged Off,8792,Short Term,7330.0,10+ years,Own Home,19982.0,Home Improvements,56.95,21.1,NaN,7,0,650,40651,0.0,0.0
19,753d4c56-3e8b-4fa6-a920-c7df31f6777f,df542e57-2fe5-4e4e-85d1-0e85eebcd326,Charged Off,10958,Long Term,6820.0,9 years,Home Mortgage,53812.0,Debt Consolidation,995.52,15.3,NaN,13,0,12336,21123,0.0,0.0

In [4]:
raw_data.describe()

,Current Loan Amount,Credit Score,Annual Income,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Bankruptcies,Tax Liens
count,1.111070e+05,89769.000000,8.976900e+04,111107.000000,52104.000000,111107.000000,111107.000000,1.111070e+05,110879.00000,111096.000000
mean,1.147718e+07,1075.795029,7.248600e+04,18.201003,34.902272,11.125105,0.168027,1.548314e+04,0.11766,0.029353
std,3.185508e+07,1474.133505,5.593094e+04,7.014495,21.970696,5.010267,0.484212,1.982115e+04,0.35142,0.260575
min,4.910000e+02,585.000000,4.033000e+03,3.600000,0.000000,0.000000,0.000000,0.000000e+00,0.00000,0.000000
25%,8.162000e+03,705.000000,4.468800e+04,13.500000,16.000000,8.000000,0.000000,5.905000e+03,0.00000,0.000000
50%,1.418300e+04,724.000000,6.175200e+04,16.900000,32.000000,10.000000,0.000000,1.102700e+04,0.00000,0.000000
75%,2.382200e+04,741.000000,8.688700e+04,21.700000,51.000000,14.000000,0.000000,1.933800e+04,0.00000,0.000000
max,1.000000e+08,7510.000000,8.713547e+06,70.500000,176.000000,76.000000,15.000000,1.730472e+06,7.00000,15.000000

In [6]:
# remove the duplicate rows of Loan ID column
df = pd.DataFrame(raw_data)
if df["Loan ID"].duplicated().any():
    df.drop_duplicates(subset=["Loan ID"], keep='first', inplace=True)
df.count()

Loan ID                         88910
Customer ID                     88910
Loan Status                     88910
Current Loan Amount             88910
Term                            88910
Credit Score                    67572
Years in current job            88910
Home Ownership                  88910
Annual Income                   67572
Purpose                         88910
Monthly Debt                    88910
Years of Credit History         88910
Months since last delinquent    40404
Number of Open Accounts         88910
Number of Credit Problems       88910
Current Credit Balance          88910
Maximum Open Credit             88910
Bankruptcies                    88718
Tax Liens                       88902
dtype: int64

In [7]:
df.dtypes

Loan ID                          object
Customer ID                      object
Loan Status                      object
Current Loan Amount               int64
Term                             object
Credit Score                    float64
Years in current job             object
Home Ownership                   object
Annual Income                   float64
Purpose                          object
Monthly Debt                     object
Years of Credit History         float64
Months since last delinquent    float64
Number of Open Accounts           int64
Number of Credit Problems         int64
Current Credit Balance            int64
Maximum Open Credit              object
Bankruptcies                    float64
Tax Liens                       float64
dtype: object

In [9]:
# remove non-digit characters in Monthly Debt column and convert to numeric values
df["Monthly Debt"] = df["Monthly Debt"].replace('[^0-9.]', '', regex=True)
df["Monthly Debt"] = pd.to_numeric(df["Monthly Debt"], errors='coerce')
df["Monthly Debt"].dtypes

dtype('float64')

In [10]:
# convert Maximum Open Credit column to numeric
df["Maximum Open Credit"] = pd.to_numeric(df["Maximum Open Credit"], errors='coerce')
df["Maximum Open Credit"].dtypes

dtype('float64')

In [11]:
# convert Months since last deliquent column to numeric
df["Months since last delinquent"] = pd.to_numeric(df["Months since last delinquent"], errors='coerce')

In [12]:
# convert Bankruptcies column to numeric
df["Bankruptcies"] = pd.to_numeric(df["Bankruptcies"], errors='coerce')

In [13]:
# convert Tax Liens column to numeric
df["Tax Liens"] = pd.to_numeric(df["Tax Liens"], errors='coerce')

In [14]:
# clean missing data in columns Credit Score and Annual Income
df["Credit Score"] = df["Credit Score"].fillna(df["Credit Score"].median())
df["Annual Income"] = df["Annual Income"].fillna(df["Annual Income"].mean())

In [15]:
# clip outlier in Credit Score
credit_score_limit = 800
while (any(df["Credit Score"]>credit_score_limit)):
        df.loc[df["Credit Score"]>credit_score_limit, "Credit Score"] = df.loc[df["Credit Score"]>credit_score_limit, "Credit Score"] / 10

In [17]:
# Convert string to numeric in column Years in current job
df["Years in current job"] = df["Years in current job"].astype('str')
df.loc[df["Years in current job"]=='< 1 year', "Years in current job"] = '0'
df.loc[df["Years in current job"]=='n/a', "Years in current job"] = '0'
df.loc[df["Years in current job"]=='10+ years', "Years in current job"] = '10'
df["Years in current job"] = df["Years in current job"].replace('[^0-9.]', '', regex=True)
df["Years in current job"] = df["Years in current job"].fillna('0')