In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib

matplotlib.style.use('ggplot') # Look Pretty
%matplotlib inline

def plotDecisionBoundary(model, X, y):
  fig = plt.figure()
  ax = fig.add_subplot(111)

  padding = 0.6
  resolution = 0.0025
  colors = ['royalblue','forestgreen','ghostwhite']

  # Calculate the boundaris
  x_min, x_max = X[:, 0].min(), X[:, 0].max()
  y_min, y_max = X[:, 1].min(), X[:, 1].max()
  x_range = x_max - x_min
  y_range = y_max - y_min
  x_min -= x_range * padding
  y_min -= y_range * padding
  x_max += x_range * padding
  y_max += y_range * padding

  # Create a 2D Grid Matrix. The values stored in the matrix
  # are the predictions of the class at at said location
  xx, yy = np.meshgrid(np.arange(x_min, x_max, resolution),
                       np.arange(y_min, y_max, resolution))

  # What class does the classifier say?
  Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
  Z = Z.reshape(xx.shape)

  # Plot the contour map
  cs = plt.contourf(xx, yy, Z, cmap=plt.cm.terrain)

  # Plot the test original points as well...
  for label in range(len(np.unique(y))):
    indices = np.where(y == label)
    plt.scatter(X[indices, 0], X[indices, 1], c=colors[label], label=str(label), alpha=0.8)

  p = model.get_params()
  plt.axis('tight')
  plt.title('K = ' + str(p['n_neighbors']))

In [2]:
# 
# TODO: Load up the dataset into a variable called X. Check the .head and
# compare it to the file you loaded in a text editor. Make sure you're
# loading your data properly--don't fail on the 1st step!
#
# .. your code here ..
datafile = "./Datasets/wheat.data"
X = pd.read_csv(datafile, header=0)
X.head()

,id,area,perimeter,compactness,length,width,asymmetry,groove,wheat_type
0,0,15.26,14.84,0.8710,5.763,3.312,2.221,5.220,kama
1,1,14.88,14.57,0.8811,5.554,3.333,1.018,4.956,kama
2,2,14.29,14.09,0.9050,5.291,3.337,2.699,4.825,kama
3,3,13.84,13.94,0.8955,5.324,3.379,2.259,4.805,kama
4,4,16.14,14.99,0.9034,5.658,3.562,1.355,5.175,kama

In [3]:
#
# TODO: Copy the 'wheat_type' series slice out of X, and into a series
# called 'y'. Then drop the original 'wheat_type' column from the X
#
# .. your code here ..
y = pd.DataFrame(X.wheat_type)
X = X.drop(labels=['wheat_type'], axis=1)
y

    wheat_type
0         kama
1         kama
2         kama
3         kama
4         kama
5         kama
6         kama
7     canadian
8         kama
9         kama
10        kama
11        kama
12        kama
13        kama
14        kama
15        kama
16        kama
17        kama
18        kama
19        kama
20        kama
21        kama
22        kama
23        kama
24        kama
25        kama
26        kama
27        kama
28        kama
29        kama
..         ...
180   canadian
181   canadian
182   canadian
183   canadian
184   canadian
185   canadian
186   canadian
187   canadian
188   canadian
189   canadian
190   canadian
191   canadian
192   canadian
193   canadian
194   canadian
195   canadian
196   canadian
197   canadian
198   canadian
199   canadian
200   canadian
201   canadian
202   canadian
203   canadian
204   canadian
205   canadian
206   canadian
207   canadian
208   canadian
209   canadian

[210 rows x 1 columns]

In [4]:
# TODO: Do a quick, "ordinal" conversion of 'y'. In actuality our
# classification isn't ordinal, but just as an experiment...
#
# .. your code here ..
y['wheat_type'] = y.wheat_type.astype("category").cat.codes
y

     wheat_type
0             1
1             1
2             1
3             1
4             1
5             1
6             1
7             0
8             1
9             1
10            1
11            1
12            1
13            1
14            1
15            1
16            1
17            1
18            1
19            1
20            1
21            1
22            1
23            1
24            1
25            1
26            1
27            1
28            1
29            1
..          ...
180           0
181           0
182           0
183           0
184           0
185           0
186           0
187           0
188           0
189           0
190           0
191           0
192           0
193           0
194           0
195           0
196           0
197           0
198           0
199           0
200           0
201           0
202           0
203           0
204           0
205           0
206           0
207           0
208           0
209           0

[210 rows x 1 columns]

In [5]:
#
# TODO: Basic nan munging. Fill each row's nans with the mean of the feature
#
# .. your code here ..
X.describe()

/Users/Jerry/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,id,area,perimeter,compactness,length,width,asymmetry,groove
count,210.000000,210.000000,210.000000,207.000000,210.000000,209.000000,210.000000,206.000000
mean,104.500000,14.847524,14.559286,0.871280,5.563918,3.281440,3.693530,5.407529
std,60.765944,2.909699,1.305959,0.023306,0.719594,0.419907,1.495112,0.532330
min,0.000000,10.590000,12.410000,0.808100,0.818900,2.630000,0.765100,3.485000
25%,52.250000,12.270000,13.450000,NaN,5.244750,NaN,2.600250,NaN
50%,104.500000,14.355000,14.320000,NaN,5.518000,NaN,3.599000,NaN
75%,156.750000,17.305000,15.715000,NaN,5.979750,NaN,4.768750,NaN
max,209.000000,21.180000,17.250000,0.918300,6.675000,5.325000,8.456000,6.735000

In [8]:
X.compactness.fillna(X.compactness.mean())
X.width.fillna(X.width.mean())
X.groove.fillna(X.groove.mean())
X.describe()

AttributeError: 'Series' object has no attribute 'compactness'