In [1]:
import pandas as pd
import numpy as np

In [2]:
#
# TODO:
# Load up the dataset, setting correct header labels.
#
# .. your code here ..
datafile = './Datasets/census.data'
header = ['education', 'age', 'capital-gain', 'race', 'capital-loss', 'hours-per-week', 'sex', 'classification']
df = pd.read_csv(datafile, names=header)
df

,education,age,capital-gain,race,capital-loss,hours-per-week,sex,classification
0,Bachelors,39,2174,White,0,40,Male,<=50K
1,Bachelors,50,?,White,0,13,Male,<=50K
2,HS-grad,38,?,White,0,40,Male,<=50K
3,11th,53,?,Black,0,40,Male,<=50K
4,Bachelors,28,0,Black,0,40,Female,<=50K
5,Masters,37,0,White,0,40,Female,<=50K
6,9th,49,0,Black,0,16,Female,<=50K
7,HS-grad,52,0,White,0,45,Male,>50K
8,Masters,31,14084,White,0,50,Female,>50K
9,Bachelors,42,5178,White,0,40,Male,>50K
10,Some-college,37,0,Black,0,80,Male,>50K
11,Bachelors,30,0,Asian-Pac-Islander,0,40,Male,>50K
12,Bachelors,23,0,White,0,30,Female,<=50K
13,7th-8th,34,0,Amer-Indian-Eskimo,0,45,Male,<=50K
14,HS-grad,25,0,White,0,35,Male,<=50K
15,HS-grad,32,0,White,0,40,Male,<=50K
16,11th,38,0,White,0,50,Male,<=50K
17,Masters,43,0,White,0,45,Female,>50K
18,Doctorate,40,0,White,0,60,Male,>50K
19,HS-grad,54,0,Black,0,20,Female,<=50K
20,9th,35,0,Black,0,40,Male,<=50K
21,11th,43,0,White,2042,40,Male,<=50K
22,HS-grad,59,0,White,0,40,Female,<=50K
23,Bachelors,56,0,White,0,40,Male,>50K
24,HS-grad,19,0,White,0,40,Male,<=50K
25,Some-college,54,0,Asian-Pac-Islander,0,60,Male,>50K
26,HS-grad,39,0,White,0,80,Male,<=50K
27,HS-grad,49,0,White,0,40,Male,<=50K
28,Some-college,20,0,Black,0,44,Male,<=50K
29,Bachelors,45,0,White,1408,40,Male,<=50K
...,...,...,...,...,...,...,...,...
29506,HS-grad,30,0,White,0,55,Male,<=50K
29507,10th,32,0,White,0,40,Male,<=50K
29508,Some-college,22,0,White,0,40,Male,<=50K
29509,HS-grad,31,0,White,0,40,Female,<=50K
29510,HS-grad,29,0,White,0,35,Female,<=50K
29511,Bachelors,35,0,White,0,55,Female,>50K
29512,Bachelors,30,0,Asian-Pac-Islander,0,99,Female,<=50K
29513,Doctorate,34,0,White,0,60,Male,>50K
29514,Bachelors,54,0,Asian-Pac-Islander,0,50,Male,>50K
29515,Some-college,37,0,White,0,39,Female,<=50K
29516,12th,22,0,Black,0,35,Male,<=50K
29517,Bachelors,34,0,White,0,55,Female,>50K
29518,HS-grad,30,0,Black,0,46,Male,<=50K
29519,Bachelors,38,15020,Black,0,45,Female,>50K
29520,Doctorate,71,0,White,0,10,Male,>50K
29521,HS-grad,45,0,White,0,40,Female,<=50K
29522,HS-grad,41,0,Black,0,32,Female,<=50K
29523,HS-grad,72,0,White,0,25,Male,<=50K
29524,Masters,31,0,Other,0,30,Female,<=50K
29525,HS-grad,43,0,White,0,40,Male,<=50K
29526,Some-college,43,0,White,0,40,Female,<=50K
29527,Some-college,43,0,White,0,50,Male,<=50K
29528,10th,32,0,Amer-Indian-Eskimo,0,40,Male,<=50K
29529,Masters,32,0,Asian-Pac-Islander,0,11,Male,<=50K
29530,Masters,53,0,White,0,40,Male,>50K
29531,Some-college,22,0,White,0,40,Male,<=50K
29532,HS-grad,40,0,White,0,40,Male,>50K
29533,HS-grad,58,0,White,0,40,Female,<=50K
29534,HS-grad,22,0,White,0,20,Male,<=50K
29535,HS-grad,52,15024,White,0,40,Female,>50K

In [3]:
#
# TODO:
# Use basic pandas commands to look through the dataset... get a
# feel for it before proceeding! Do the data-types of each column
# reflect the values you see when you look through the data using
# a text editor / spread sheet program? If you see 'object' where
# you expect to see 'int32' / 'float64', that is a good indicator
# that there is probably a string or missing value in a column.
# use `your_data_frame['your_column'].unique()` to see the unique
# values of each column and identify the rogue values. If these
# should be represented as nans, you can convert them using
# na_values when loading the dataframe.
#
# .. your code here ..
df.dtypes

education         object
age                int64
capital-gain      object
race              object
capital-loss       int64
hours-per-week     int64
sex               object
classification    object
dtype: object

In [4]:
df.describe()

                age  capital-loss  hours-per-week
count  29536.000000  29536.000000    29536.000000
mean      38.506094     84.957408       40.243872
std       13.811739    397.107750       12.326211
min       17.000000      0.000000        1.000000
25%       27.000000      0.000000       40.000000
50%       37.000000      0.000000       40.000000
75%       48.000000      0.000000       45.000000
max       90.000000   4356.000000       99.000000

In [5]:
df.loc[df['capital-gain']=='?', 'capital-gain']= np.nan
df

,education,age,capital-gain,race,capital-loss,hours-per-week,sex,classification
0,Bachelors,39,2174,White,0,40,Male,<=50K
1,Bachelors,50,NaN,White,0,13,Male,<=50K
2,HS-grad,38,NaN,White,0,40,Male,<=50K
3,11th,53,NaN,Black,0,40,Male,<=50K
4,Bachelors,28,0,Black,0,40,Female,<=50K
5,Masters,37,0,White,0,40,Female,<=50K
6,9th,49,0,Black,0,16,Female,<=50K
7,HS-grad,52,0,White,0,45,Male,>50K
8,Masters,31,14084,White,0,50,Female,>50K
9,Bachelors,42,5178,White,0,40,Male,>50K
10,Some-college,37,0,Black,0,80,Male,>50K
11,Bachelors,30,0,Asian-Pac-Islander,0,40,Male,>50K
12,Bachelors,23,0,White,0,30,Female,<=50K
13,7th-8th,34,0,Amer-Indian-Eskimo,0,45,Male,<=50K
14,HS-grad,25,0,White,0,35,Male,<=50K
15,HS-grad,32,0,White,0,40,Male,<=50K
16,11th,38,0,White,0,50,Male,<=50K
17,Masters,43,0,White,0,45,Female,>50K
18,Doctorate,40,0,White,0,60,Male,>50K
19,HS-grad,54,0,Black,0,20,Female,<=50K
20,9th,35,0,Black,0,40,Male,<=50K
21,11th,43,0,White,2042,40,Male,<=50K
22,HS-grad,59,0,White,0,40,Female,<=50K
23,Bachelors,56,0,White,0,40,Male,>50K
24,HS-grad,19,0,White,0,40,Male,<=50K
25,Some-college,54,0,Asian-Pac-Islander,0,60,Male,>50K
26,HS-grad,39,0,White,0,80,Male,<=50K
27,HS-grad,49,0,White,0,40,Male,<=50K
28,Some-college,20,0,Black,0,44,Male,<=50K
29,Bachelors,45,0,White,1408,40,Male,<=50K
...,...,...,...,...,...,...,...,...
29506,HS-grad,30,0,White,0,55,Male,<=50K
29507,10th,32,0,White,0,40,Male,<=50K
29508,Some-college,22,0,White,0,40,Male,<=50K
29509,HS-grad,31,0,White,0,40,Female,<=50K
29510,HS-grad,29,0,White,0,35,Female,<=50K
29511,Bachelors,35,0,White,0,55,Female,>50K
29512,Bachelors,30,0,Asian-Pac-Islander,0,99,Female,<=50K
29513,Doctorate,34,0,White,0,60,Male,>50K
29514,Bachelors,54,0,Asian-Pac-Islander,0,50,Male,>50K
29515,Some-college,37,0,White,0,39,Female,<=50K
29516,12th,22,0,Black,0,35,Male,<=50K
29517,Bachelors,34,0,White,0,55,Female,>50K
29518,HS-grad,30,0,Black,0,46,Male,<=50K
29519,Bachelors,38,15020,Black,0,45,Female,>50K
29520,Doctorate,71,0,White,0,10,Male,>50K
29521,HS-grad,45,0,White,0,40,Female,<=50K
29522,HS-grad,41,0,Black,0,32,Female,<=50K
29523,HS-grad,72,0,White,0,25,Male,<=50K
29524,Masters,31,0,Other,0,30,Female,<=50K
29525,HS-grad,43,0,White,0,40,Male,<=50K
29526,Some-college,43,0,White,0,40,Female,<=50K
29527,Some-college,43,0,White,0,50,Male,<=50K
29528,10th,32,0,Amer-Indian-Eskimo,0,40,Male,<=50K
29529,Masters,32,0,Asian-Pac-Islander,0,11,Male,<=50K
29530,Masters,53,0,White,0,40,Male,>50K
29531,Some-college,22,0,White,0,40,Male,<=50K
29532,HS-grad,40,0,White,0,40,Male,>50K
29533,HS-grad,58,0,White,0,40,Female,<=50K
29534,HS-grad,22,0,White,0,20,Male,<=50K
29535,HS-grad,52,15024,White,0,40,Female,>50K

In [6]:
#
# TODO:
# Look through your data and identify any potential categorical
# features. Ensure you properly encode any ordinal and nominal
# types using the methods discussed in the chapter.
#
# Be careful! Some features can be represented as either categorical
# or continuous (numerical). Think to yourself, does it generally
# make more sense to have a numeric type or a series of categories
# for these somewhat ambigious features?
#
# .. your code here ..
df = pd.get_dummies(df, columns=['race', 'sex'])
df

,education,age,capital-gain,capital-loss,hours-per-week,classification,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White,sex_Female,sex_Male
0,Bachelors,39,2174,0,40,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,Bachelors,50,NaN,0,13,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2,HS-grad,38,NaN,0,40,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3,11th,53,NaN,0,40,<=50K,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,Bachelors,28,0,0,40,<=50K,0.0,0.0,1.0,0.0,0.0,1.0,0.0
5,Masters,37,0,0,40,<=50K,0.0,0.0,0.0,0.0,1.0,1.0,0.0
6,9th,49,0,0,16,<=50K,0.0,0.0,1.0,0.0,0.0,1.0,0.0
7,HS-grad,52,0,0,45,>50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
8,Masters,31,14084,0,50,>50K,0.0,0.0,0.0,0.0,1.0,1.0,0.0
9,Bachelors,42,5178,0,40,>50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
10,Some-college,37,0,0,80,>50K,0.0,0.0,1.0,0.0,0.0,0.0,1.0
11,Bachelors,30,0,0,40,>50K,0.0,1.0,0.0,0.0,0.0,0.0,1.0
12,Bachelors,23,0,0,30,<=50K,0.0,0.0,0.0,0.0,1.0,1.0,0.0
13,7th-8th,34,0,0,45,<=50K,1.0,0.0,0.0,0.0,0.0,0.0,1.0
14,HS-grad,25,0,0,35,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
15,HS-grad,32,0,0,40,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
16,11th,38,0,0,50,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
17,Masters,43,0,0,45,>50K,0.0,0.0,0.0,0.0,1.0,1.0,0.0
18,Doctorate,40,0,0,60,>50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
19,HS-grad,54,0,0,20,<=50K,0.0,0.0,1.0,0.0,0.0,1.0,0.0
20,9th,35,0,0,40,<=50K,0.0,0.0,1.0,0.0,0.0,0.0,1.0
21,11th,43,0,2042,40,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
22,HS-grad,59,0,0,40,<=50K,0.0,0.0,0.0,0.0,1.0,1.0,0.0
23,Bachelors,56,0,0,40,>50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
24,HS-grad,19,0,0,40,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
25,Some-college,54,0,0,60,>50K,0.0,1.0,0.0,0.0,0.0,0.0,1.0
26,HS-grad,39,0,0,80,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
27,HS-grad,49,0,0,40,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
28,Some-college,20,0,0,44,<=50K,0.0,0.0,1.0,0.0,0.0,0.0,1.0
29,Bachelors,45,0,1408,40,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29506,HS-grad,30,0,0,55,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29507,10th,32,0,0,40,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29508,Some-college,22,0,0,40,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29509,HS-grad,31,0,0,40,<=50K,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29510,HS-grad,29,0,0,35,<=50K,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29511,Bachelors,35,0,0,55,>50K,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29512,Bachelors,30,0,0,99,<=50K,0.0,1.0,0.0,0.0,0.0,1.0,0.0
29513,Doctorate,34,0,0,60,>50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29514,Bachelors,54,0,0,50,>50K,0.0,1.0,0.0,0.0,0.0,0.0,1.0
29515,Some-college,37,0,0,39,<=50K,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29516,12th,22,0,0,35,<=50K,0.0,0.0,1.0,0.0,0.0,0.0,1.0
29517,Bachelors,34,0,0,55,>50K,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29518,HS-grad,30,0,0,46,<=50K,0.0,0.0,1.0,0.0,0.0,0.0,1.0
29519,Bachelors,38,15020,0,45,>50K,0.0,0.0,1.0,0.0,0.0,1.0,0.0
29520,Doctorate,71,0,0,10,>50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29521,HS-grad,45,0,0,40,<=50K,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29522,HS-grad,41,0,0,32,<=50K,0.0,0.0,1.0,0.0,0.0,1.0,0.0
29523,HS-grad,72,0,0,25,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29524,Masters,31,0,0,30,<=50K,0.0,0.0,0.0,1.0,0.0,1.0,0.0
29525,HS-grad,43,0,0,40,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29526,Some-college,43,0,0,40,<=50K,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29527,Some-college,43,0,0,50,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29528,10th,32,0,0,40,<=50K,1.0,0.0,0.0,0.0,0.0,0.0,1.0
29529,Masters,32,0,0,11,<=50K,0.0,1.0,0.0,0.0,0.0,0.0,1.0
29530,Masters,53,0,0,40,>50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29531,Some-college,22,0,0,40,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29532,HS-grad,40,0,0,40,>50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29533,HS-grad,58,0,0,40,<=50K,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29534,HS-grad,22,0,0,20,<=50K,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29535,HS-grad,52,15024,0,40,>50K,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [7]:
ordered_classifications = ['<=50K', '>50K']
df.classification = df.classification.astype('category', ordered=True, categories=ordered_classifications).cat.codes
df

,education,age,capital-gain,capital-loss,hours-per-week,classification,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White,sex_Female,sex_Male
0,Bachelors,39,2174,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,Bachelors,50,NaN,0,13,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2,HS-grad,38,NaN,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3,11th,53,NaN,0,40,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,Bachelors,28,0,0,40,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
5,Masters,37,0,0,40,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
6,9th,49,0,0,16,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
7,HS-grad,52,0,0,45,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
8,Masters,31,14084,0,50,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0
9,Bachelors,42,5178,0,40,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
10,Some-college,37,0,0,80,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0
11,Bachelors,30,0,0,40,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0
12,Bachelors,23,0,0,30,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
13,7th-8th,34,0,0,45,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
14,HS-grad,25,0,0,35,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
15,HS-grad,32,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
16,11th,38,0,0,50,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
17,Masters,43,0,0,45,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0
18,Doctorate,40,0,0,60,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
19,HS-grad,54,0,0,20,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
20,9th,35,0,0,40,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
21,11th,43,0,2042,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
22,HS-grad,59,0,0,40,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
23,Bachelors,56,0,0,40,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
24,HS-grad,19,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
25,Some-college,54,0,0,60,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0
26,HS-grad,39,0,0,80,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
27,HS-grad,49,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
28,Some-college,20,0,0,44,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
29,Bachelors,45,0,1408,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29506,HS-grad,30,0,0,55,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29507,10th,32,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29508,Some-college,22,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29509,HS-grad,31,0,0,40,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29510,HS-grad,29,0,0,35,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29511,Bachelors,35,0,0,55,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29512,Bachelors,30,0,0,99,0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
29513,Doctorate,34,0,0,60,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29514,Bachelors,54,0,0,50,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0
29515,Some-college,37,0,0,39,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29516,12th,22,0,0,35,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
29517,Bachelors,34,0,0,55,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29518,HS-grad,30,0,0,46,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
29519,Bachelors,38,15020,0,45,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0
29520,Doctorate,71,0,0,10,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29521,HS-grad,45,0,0,40,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29522,HS-grad,41,0,0,32,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
29523,HS-grad,72,0,0,25,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29524,Masters,31,0,0,30,0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
29525,HS-grad,43,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29526,Some-college,43,0,0,40,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29527,Some-college,43,0,0,50,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29528,10th,32,0,0,40,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
29529,Masters,32,0,0,11,0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
29530,Masters,53,0,0,40,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29531,Some-college,22,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29532,HS-grad,40,0,0,40,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29533,HS-grad,58,0,0,40,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29534,HS-grad,22,0,0,20,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29535,HS-grad,52,15024,0,40,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [8]:
df.describe()

,age,capital-loss,hours-per-week,classification,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White,sex_Female,sex_Male
count,29536.000000,29536.000000,29536.000000,29536.000000,29536.000000,29536.000000,29536.000000,29536.000000,29536.000000,29536.000000,29536.000000
mean,38.506094,84.957408,40.243872,0.229957,0.009548,0.031521,0.097847,0.008566,0.852519,0.330376,0.669624
std,13.811739,397.107750,12.326211,0.420812,0.097246,0.174724,0.297112,0.092156,0.354591,0.470357,0.470357
min,17.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,27.000000,0.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
50%,37.000000,0.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
75%,48.000000,0.000000,45.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
max,90.000000,4356.000000,99.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
df = df.dropna(axis=0).reset_index(drop=True)
df

,education,age,capital-gain,capital-loss,hours-per-week,classification,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White,sex_Female,sex_Male
0,Bachelors,39,2174,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1,Bachelors,28,0,0,40,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,Masters,37,0,0,40,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,9th,49,0,0,16,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,HS-grad,52,0,0,45,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
5,Masters,31,14084,0,50,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0
6,Bachelors,42,5178,0,40,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
7,Some-college,37,0,0,80,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0
8,Bachelors,30,0,0,40,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0
9,Bachelors,23,0,0,30,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
10,7th-8th,34,0,0,45,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
11,HS-grad,25,0,0,35,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
12,HS-grad,32,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
13,11th,38,0,0,50,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
14,Masters,43,0,0,45,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0
15,Doctorate,40,0,0,60,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
16,HS-grad,54,0,0,20,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
17,9th,35,0,0,40,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
18,11th,43,0,2042,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
19,HS-grad,59,0,0,40,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
20,Bachelors,56,0,0,40,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
21,HS-grad,19,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
22,Some-college,54,0,0,60,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0
23,HS-grad,39,0,0,80,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
24,HS-grad,49,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
25,Some-college,20,0,0,44,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
26,Bachelors,45,0,1408,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
27,Some-college,30,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
28,Some-college,22,0,0,15,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
29,11th,48,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29502,HS-grad,30,0,0,55,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29503,10th,32,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29504,Some-college,22,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29505,HS-grad,31,0,0,40,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29506,HS-grad,29,0,0,35,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29507,Bachelors,35,0,0,55,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29508,Bachelors,30,0,0,99,0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
29509,Doctorate,34,0,0,60,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29510,Bachelors,54,0,0,50,1,0.0,1.0,0.0,0.0,0.0,0.0,1.0
29511,Some-college,37,0,0,39,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29512,12th,22,0,0,35,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
29513,Bachelors,34,0,0,55,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29514,HS-grad,30,0,0,46,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
29515,Bachelors,38,15020,0,45,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0
29516,Doctorate,71,0,0,10,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29517,HS-grad,45,0,0,40,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29518,HS-grad,41,0,0,32,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
29519,HS-grad,72,0,0,25,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29520,Masters,31,0,0,30,0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
29521,HS-grad,43,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29522,Some-college,43,0,0,40,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29523,Some-college,43,0,0,50,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29524,10th,32,0,0,40,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
29525,Masters,32,0,0,11,0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
29526,Masters,53,0,0,40,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29527,Some-college,22,0,0,40,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29528,HS-grad,40,0,0,40,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29529,HS-grad,58,0,0,40,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
29530,HS-grad,22,0,0,20,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
29531,HS-grad,52,15024,0,40,1,0.0,0.0,0.0,0.0,1.0,1.0,0.0